### ISSUE TITLE
Mixins and autobinding support

### ISSUE THREAD

**Issue by tachuris** [jankuca/reacto#1]
Since version 0.13, React supports ES6 classes (see http://facebook.github.io/react/docs/reusable-components.html#es6-classes) but these don't autobind methods nor support mixins. Does reacto support autobinding and mixins?

**Comment by jankuca** [comment]
Nope, sorry. Plus with the native ES6 class support in React, Reacto is quite done too.

**Comment by tachuris** [comment]
[Mixins Are Dead. Long Live Composition](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750) :)
